name: my-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deps install
        run: make install

      - name: Linter check
        run: make lint
      
      - name: Test run
        run: make test