name: my-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  test:
    steps:
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v2
    with:
      token: ${{ secrets.CODECLIMATE_TEST_ID }} # not required for public repos
      files: ./coverage1.xml,./coverage2.xml # optional
      flags: unittests # optional
      name: codecov-umbrella # optional
      fail_ci_if_error: true # optional (default = false)
      verbose: true # optional (default = false)
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deps install
        run: make install

      - name: Linter check
        run: make lint
      
      - name: Test run
        run: make test