name: my-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deps install
        run: make install

      - name: Linter check
        run: make lint
      
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: <code_climate_reporter_id>
        with:
          coverageCommand: make test
          debug: true
